### PR TITLE
adding scope parameter to options object to have ability to manage ap…

### PR DESCRIPTION
**Pull request by bershadskiy**
…p scopes

CREST api has new available scopes like characterContactsRead and characterContactsWrite

### CODE REVIEW

**Comment by tmikoss** [comment]
Apologies for the delayed merge - I've quit the game and, frankly, forgotten about this project.

**Comment by tmikoss** [comment]
@bershadskiy I've pushed version 0.1.1 of the package that includes this change.

But seeing that I'm no longer actively working with neither EvE nor Meteor, would you like to take over the package (if atmosphere even allows it)?

**Comment by bershadskiy** [comment]
wow. look's like i lost info from author.
currently i can't contribute here. if any changes happens, i'll try to fix any issues. plz, assign to me any issues and i'll try to fix them.

**Comment by janat08** [comment]
@bershadskiy What info did you lose, I've made a pull request for concurrent SSO, and it's crashing since i'm trying to overwrite Accounts object without knowing how packages work.

**Pull request merged**
